name: Android Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Decode Keystore
        run: |
          mkdir -p android/app
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Update signingConfig in build.gradle
        run: |
          sed -i '/signingConfig = signingConfigs.getByName("debug")/d' android/app/build.gradle.kts
          cat << EOF >> android/app/build.gradle.kts
          
          signingConfigs {
              create("release") {
                  storeFile = file("upload-keystore.jks")
                  storePassword = "${{ secrets.STORE_PASSWORD }}"
                  keyAlias = "${{ secrets.KEY_ALIAS }}"
                  keyPassword = "${{ secrets.KEY_PASSWORD }}"
              }
          }
          
          android {
              buildTypes {
                  getByName("release") {
                      signingConfig = signingConfigs.getByName("release")
                  }
              }
          }
          EOF

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK to GitHub Packages
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 